apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: # kpt-merge: argocd/free5gc-core
  name: free5gc-core
  namespace: argocd
  annotations:
    internal.kpt.dev/upstream-identifier: 'argoproj.io|Application|argocd|free5gc-core'
spec:
  project: default
  source:
    chart: free5gc-controlplane
    repoURL: ghcr.io/infinitydon
    targetRevision: 0.0.1 # kpt-set: ${helm-chart-version}
    helm:
      releaseName: core5g # kpt-set: ${helm-release-name}
      valuesObject:
        dnn: internet # kpt-set: ${dnn}
        amf:
          n2:
            multusIP: 10.1.3.16 # kpt-set: ${amf-multus-n2-ip}
            multusNetworkMask: 24 # kpt-set: ${amf-n2-netmask}
            routeGw: 10.1.3.1 # kpt-set: ${amf-n2-route-gw}
        gnb:
          N2subnetCIDR: 10.0.5.0/24 # kpt-set: ${gnb-n2-subnet-cidr} 
        ue:
          imsi: '"208930000000003"' # kpt-set: ${ue-imsi}
        smf:
          n4:
            multusIP: 10.1.4.16 # kpt-set: ${smf-multus-n4-ip}
            multusNetworkMask: 24 # kpt-set: ${smf-n4-netmask}
            routeGw: 10.1.4.1 # kpt-set: ${smf-n4-route-gw}
        upf:
          N4subnetCIDR: 10.2.4.0/24 # kpt-set: ${upf-n4-subnet-cidr}
        upf1:
          n3:
            multusIP: 10.2.3.16 # kpt-set: ${upf1-multus-n3-ip}
          n4:
            multusIP: 10.2.4.16 # kpt-set: ${upf1-multus-n4-ip}
        upf2:
          n3:
            multusIP: 10.2.3.17 # kpt-set: ${upf2-multus-n3-ip}
          n4:
            multusIP: 10.2.4.17 # kpt-set: ${upf2-multus-n4-ip}
        multus:
          n2dev: eth1 # kpt-set: ${multus-n2-dev}
          n4dev: eth2 # kpt-set: ${multus-n4-dev}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: telco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    - ServerSideApply=true,Validate=false
