apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: oai-core/nrf-core
  name: nrf-core
  namespace: oai-core
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|oai-core|nrf-core'
spec:
  provider: nrf.openairinterface.org
