apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: oai-core/udm-core
  name: udm-core
  namespace: oai-core
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|oai-core|udm-core'
spec:
  provider: udm.openairinterface.org
